# Generated by Django 2.1.7 on 2019-03-14 19:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('realname', models.TextField(blank=True, null=True)),
                ('profile', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('release_id', models.AutoField(primary_key=True, serialize=False)),
                ('released', models.DateTimeField(default=datetime.datetime.now)),
                ('title', models.TextField()),
                ('country', models.CharField(blank=True, max_length=256, null=True)),
                ('genre', models.CharField(blank=True, max_length=256, null=True)),
                ('artists', models.ManyToManyField(to='collection.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=128)),
                ('title', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField()),
                ('release_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.Release')),
            ],
        ),
    ]
