# Generated by Django 2.1.7 on 2019-03-14 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='release_id',
            new_name='release',
        ),
    ]
